const QUERY_KEYS = {
  USE_PROJECTS: "USE_PROJECTS",
  USE_CARDS_BY_PROJECT_SLUG: "USE_CARDS_BY_PROJECT_SLUG",
  USE_WORKSPACE: "USE_WORKSPACE",
  USE_SEARCH: "USE_SEARCH",
};

export { QUERY_KEYS };
