const QUERY_KEYS = {
  USE_PROJECTS: "USE_PROJECTS",
  USE_CARDS_BY_PROJECT_SLUG: "USE_CARDS_BY_PROJECT_SLUG",
  USE_WORKSPACE: "USE_WORKSPACE",
  USE_SEARCH: "USE_SEARCH",
  USE_USER_NOTIFICATIONS_SETTINGS: "USE_USER_NOTIFICATIONS_SETTINGS",
  USE_PERMISSIONS: "USE_PERMISSIONS",
  USE_WORKSPACE_DETAILS: "USE_WORKSPACE_DETAILS",
  USE_WORKSPACE_ROLES: "USE_WORKSPACE_ROLES",
  USE_PROJECT_DETAILS: "USE_PROJECT_DETAILS",
};

export { QUERY_KEYS };
